# Generated by Django 4.2.7 on 2023-11-24 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_packing_cost_product_tax_alter_product_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='packing_cost',
            new_name='shipping_fee',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tax',
        ),
    ]
