# Generated by Django 4.2.7 on 2023-11-30 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_searchhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BrandName', models.CharField(max_length=255, verbose_name='Brand Name')),
                ('Deatils', models.CharField(max_length=255, verbose_name='Deatils')),
                ('Sizes', models.CharField(max_length=255, verbose_name='Sizes')),
                ('MRP', models.IntegerField(verbose_name='MRP')),
                ('SellPrice', models.IntegerField(verbose_name='SellPrice')),
                ('Discount', models.IntegerField(verbose_name='Discount')),
                ('Category', models.CharField(max_length=255, verbose_name='Category')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.main_category'),
        ),
    ]
