# Generated by Django 4.2.7 on 2023-11-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_csv_alter_category_main_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CSV',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_information',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Tags',
        ),
        migrations.RemoveField(
            model_name='product',
            name='section',
        ),
        migrations.AlterField(
            model_name='product',
            name='featured_image',
            field=models.ImageField(blank=True, upload_to='media/featured_image'),
        ),
    ]
