# Generated by Django 4.2.7 on 2023-11-30 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_delete_csv_remove_product_product_information_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_category',
            name='category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='main_category',
        ),
        migrations.DeleteModel(
            name='Main_Category',
        ),
        migrations.DeleteModel(
            name='Sub_category',
        ),
    ]
