# Generated by Django 4.2.7 on 2023-12-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_sub_category_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='featured_image',
            field=models.ImageField(blank=True, default='media/featured_image/default.jpg', null=True, upload_to='media/featured_image'),
        ),
    ]
